name: Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Create config stub
      run: |
        mkdir configs/release
        echo '' >> configs/release/bot.yml
    - name: Build image
      run: make ip=0.0.0.0