name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - uses: actions/cache@v3
      id: cache
      with:
        path: |
          ${{ $GOCACHE }}
          ${{ $GOMODCACHE }}
          ${{ $GOPATH }}/bin
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

    - name: Install goose
      if: steps.cache.outputs.cache-hit != 'true'
      run: go install github.com/pressly/goose/v3/cmd/goose@latest

    - name: Test
      run: make test
